version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb+srv://rugveddeva:rugveddeva@cluster0.red6pey.mongodb.net/social-media?retryWrites=true&w=majority
      - JWT_SECRET=supersecretkey
      - JWT_REFRESH_SECRET=superrefreshkey
      - FRONTEND_URL=https://viora-org.netlify.app/
      - STRIPE_SECRET_KEY=sk_test_51S8fFOAISo5oSLyd7swQ9rZQBfKq6o2voRQQT2PHZRENnAJdaBTLhyT0DKpFWvzovLQfJn5fWIArCLfshpahqhei00K1gKmGYA
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
